-- ============================================
-- SKEMA DATABASE - CAT SKD TIU Subtes
-- ============================================
-- Jalankan seluruh query ini di Supabase SQL Editor

-- 1. Tabel Bank Soal (questions)
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,              -- Konten soal (HTML, termasuk gambar inline)
    question_type TEXT NOT NULL DEFAULT 'text', -- Tipe soal (selalu 'text' karena gambar inline di rich text editor)
    options JSONB NOT NULL,             -- {"A": "...", "B": "...", "C": "...", "D": "...", "E": "..."}
    correct_answer VARCHAR(1) NOT NULL, -- 'A', 'B', 'C', 'D', 'E'
    option_scores JSONB,                -- TKP-only: {"A":1..5,"B":1..5,"C":1..5,"D":1..5,"E":1..5} sebagai permutasi {1,2,3,4,5}. NULL untuk TWK/TIU atau TKP yang belum di-set bobotnya (lihat tkp-scoring-spec.md §5/§9/§6).
    explanation TEXT NOT NULL,          -- Pembahasan (HTML, termasuk gambar inline)
    image_url TEXT,                     -- Deprecated: gambar sekarang inline di content
    explanation_image_url TEXT,         -- Deprecated: gambar sekarang inline di explanation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Paket Soal (question_packs)
CREATE TABLE IF NOT EXISTS question_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    passing_grade INTEGER NOT NULL DEFAULT 85, -- Nilai absolut (contoh: 85 poin)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabel Relasi Paket & Soal (pack_questions)
CREATE TABLE IF NOT EXISTS pack_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
    question_number INTEGER NOT NULL,
    UNIQUE(pack_id, question_id),
    -- Race-safe (2026-08-12): satu paket TIDAK boleh punya 2 soal bernomor
    -- sama. Menutup race window max+1 antar tab admin — insert duplikat
    -- ditolak DB (error 23505) dan server retry dgn nomor baru. Untuk
    -- existing install: jalankan migration-004 DULU (renumber paket yang
    -- sudah terlanjur ber-question_number duplikat), lalu constraint ini.
    UNIQUE(pack_id, question_number)
);

-- 4. Tabel Hasil Ujian (exam_results)
CREATE TABLE IF NOT EXISTS exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    participant_name TEXT NOT NULL,
    score INTEGER NOT NULL,             -- Skor absolut (bukan persentase)
    status TEXT NOT NULL,               -- 'Lulus PG' atau 'Tidak Lulus PG'
    answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================
-- TABEL ADMIN AUTH (CMS protection)
-- ============================================
-- Stores admin user credentials for CMS access (bank-soal, kelola-soal,
-- paket-soal, paket-detail). Password stored as bcrypt hash (cost 10).
-- Bootstrap: insert via env vars on first cold-start (see src/server.js).
-- Recovery: if password lost, TRUNCATE this table + redeploy with
-- BOOTSTRAP_ADMIN_* env vars to recreate.

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,       -- UNIQUE untuk race-safe bootstrap
    password_hash VARCHAR(255) NOT NULL,        -- bcrypt hash (cost 10, ~60 chars)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE      -- nullable; updated on each successful login
);

-- Index untuk fast username lookup di login endpoint
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

-- ============================================
-- CATATAN PERUBAHAN
-- ============================================
-- - Kolom image_url dan explanation_image_url sekarang selalu NULL karena gambar
--   diupload langsung ke Vercel Blob dan di-embed sebagai tag <img> di dalam
--   kolom content dan explanation.
-- - Kolom question_type sekarang selalu bernilai 'text' karena tidak ada lagi
--   pemisahan tipe soal (semua menggunakan rich text editor).
-- - Constraint UNIQUE(pack_id, question_number) pada pack_questions (2026-08-12):
--   menutup race window antar tab admin — insert duplikat ditolak DB (error
--   23505) dan server retry dgn nomor baru (lihat specs/pack-question-order-spec.md).
--   Untuk existing install, jalankan migration-004 DULU (renumber paket lama yang
--   sudah terlanjur ber-question_number duplikat) sebelum constraint aktif.
--- Untuk migrasi data lama yang sudah memiliki gambar di image_url/explanation_image_url,
-- gambar akan tetap ditampilkan karena tag <img> akan dibaca dari kolom content
-- atau dari image_url/explanation_image_url.
--
-- ============================================
-- TKP weighted scoring (lihat tkp-scoring-spec.md §5/§6/§9)
-- ============================================
-- Kolom option_scores (JSONB, nullable) menyimpan bobot 1..5 per opsi A-E
-- untuk soal TKP (TWK/TIU tetap NULL). Invariant §6: himpunan nilainya
-- harus persis {1,2,3,4,5} (satu opsi per bobot), urutan huruf bebas —
-- admin boleh menulis permutasi apa pun (mis. A=2,B=1,C=5,D=3,E=4) lewat
-- (a) single-question modal Bobot TKP, atau
-- (b) baris `Bobot: A=#,B=#,C=#,D=#,E=#` dalam bulk-import.
-- Skor per soal = option_scores[answer] (TKP) atau jawaban_benar ? 5 : 0 (biner).
--
-- Untuk tabel yang sudah ada sebelum kolom ini ditambahkan, jalankan
-- migrasi terpisan (idempoten):
--   ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_scores JSONB;

-- ============================================
-- PACK SUBTEST PICKER + PER-SUBTEST THRESHOLDS
-- ============================================
-- Mendukung checkbox picker 1-3 subtes di public/paket-soal.html:
--   - 1 subtes  : 1 passing grade input (paket khusus subtes itu saja)
--   - 2 subtes  : 2 passing grade inputs (combo 2-subtes)
--   - 3 subtes  : 3 passing grade inputs (combo 3-subtes / paket lengkap)
-- ketika user klik "Lihat soal" → paket-detail.html hanya menampilkan soal
-- dengan question_type yang termasuk dalam pack.subtests.
--
-- Kolom:
--   subtests            TEXT[]  daftar token subtes ['TWK','TIU'] dst.
--                                panjang 1-3 sesuai pilihan admin
--   subtest_thresholds  JSONB   peta {TWK:N, TIU:N, TKP:N} per-subtes
--                                default Indonesia: TWK=65, TIU=80, TKP=166
--
-- Backward compat: pack lama auto-default ke 3 subtes + threshold standar,
-- sehingga review.js + paket-detail.js tetap bekerja tanpa perubahan.
ALTER TABLE question_packs
  ADD COLUMN IF NOT EXISTS subtests TEXT[] NOT NULL DEFAULT ARRAY['TWK','TIU','TKP'],
  ADD COLUMN IF NOT EXISTS subtest_thresholds JSONB NOT NULL DEFAULT
    '{"TWK":65,"TIU":80,"TKP":166}'::jsonb;

-- ============================================
-- PACK VISIBILITY (2026-08-15, lihat specs/pack-visibility-spec.md)
-- ============================================
-- Kontrol penayangan paket soal di select-pack.html:
--   - 'public'   → tampil + bisa dikerjakan semua orang
--   - 'admin'    → tampil + hanya bisa dikerjakan admin (login via
--                  cookie toskd_admin_sess, dideteksi server-side)
--   - 'archived' → TIDAK tampil di select-pack + TIDAK bisa dikerjakan
--                  siapa pun; CMS tetap melihatnya (untuk un-arsip)
-- DEFAULT 'public' → existing rows otomatis terisi Publik (requirement).
-- App memakai service_role (bypass RLS) → RLS/GRANT tidak berubah.
ALTER TABLE question_packs
  ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'public';

-- CHECK constraint (idempotent via DO block — ADD CONSTRAINT tidak punya
-- IF NOT EXISTS). Mencegah nilai tak dikenal lewat API langsung.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'question_packs_visibility_check'
      AND conrelid = 'question_packs'::regclass
  ) THEN
    ALTER TABLE question_packs
      ADD CONSTRAINT question_packs_visibility_check
      CHECK (visibility IN ('public', 'admin', 'archived'));
  END IF;
END $$;

-- ============================================
-- ROW LEVEL SECURITY (2026-08-12, align dengan prod)
-- ============================================
-- Prod mengaktifkan RLS di 5 tabel + deny policies di admins. Tanpa RLS,
-- default privileges Supabase (GRANT ALL ke anon/authenticated) membuat tabel
-- terbaca publik via PostgREST (anon key publik) — termasuk bank jawaban dan
-- password hash admin. App memakai service_role (bypass RLS) → perilaku app
-- TIDAK berubah; ini murni postur keamanan (lihat migration-005).
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pack_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Deny policies admins (idempotent via DO block — CREATE POLICY tidak punya
-- IF NOT EXISTS)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'admins'
                   AND policyname = 'deny_anon_admins') THEN
    CREATE POLICY deny_anon_admins ON admins
      TO anon USING (false) WITH CHECK (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'admins'
                   AND policyname = 'deny_authenticated_admins') THEN
    CREATE POLICY deny_authenticated_admins ON admins
      TO authenticated USING (false) WITH CHECK (false);
  END IF;
END $$;

-- ============================================
-- GRANT API ROLES (2026-08-12, align dengan hosted/prod)
-- ============================================
-- Hosted Supabase memberi default privileges penuh ke anon/authenticated/
-- service_role; stack lokal TIDAK (hanya TRUNCATE/REFERENCES/TRIGGER). Tanpa
-- grant ini, app yang dipointing ke lokal gagal dengan 42501 permission denied
-- (lihat migration-006). Idempotent. RLS (blok di atas) tetap pengaman:
-- anon/authenticated diblokir RLS, service_role bypass.
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
