-- 1. Tabel Bank Soal (questions)
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    question_type TEXT NOT NULL, -- 'text', 'math', 'figural'
    options JSONB NOT NULL, -- {"A": "...", "B": "...", "C": "...", "D": "...", "E": "..."}
    correct_answer VARCHAR(1) NOT NULL, -- 'A', 'B', 'C', 'D', 'E'
    explanation TEXT NOT NULL,
    image_url TEXT,
    explanation_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Paket Soal (question_packs)
CREATE TABLE IF NOT EXISTS question_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    passing_grade INTEGER NOT NULL DEFAULT 85,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabel Relasi Paket & Soal (pack_questions)
CREATE TABLE IF NOT EXISTS pack_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
    question_number INTEGER NOT NULL,
    UNIQUE(pack_id, question_id)
);

-- 4. Tabel Hasil Ujian (exam_results)
CREATE TABLE IF NOT EXISTS exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    participant_name TEXT NOT NULL,
    score INTEGER NOT NULL,
    status TEXT NOT NULL, -- 'Lulus PG', 'Tidak Lulus PG'
    answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
