-- ============================================
-- 004-unique-pack-question-number
-- Menutup race window antar admin tab + ALIGN schema prod
-- (2026-08-12, bug-fix urutan soal paket — lihat specs/pack-question-order-spec.md)
-- ============================================
-- DUA PEKERJAAN dalam 1 migrasi:
--
-- (1) ALIGN schema `pack_questions` prod → bentuk `schema.sql`:
--     Prod dibuat via SQL Editor dengan varian LAMA: TANPA kolom `id`,
--     PRIMARY KEY komposit (pack_id, question_id). Local/dev (fresh dari
--     schema.sql) punya `id` IDENTITY PRIMARY KEY + UNIQUE(pack_id, question_id).
--     Drift ini membuat migration yang memakai `pack_questions.id` gagal di
--     prod (42703: column "id" does not exist — kejadian 2026-08-12).
--     Step 0-1 menormalkan: tambah `id` identity (backfill otomatis baris
--     existing), swap PK komposit → PK(id), tambah UNIQUE(pack_id, question_id).
--
-- (2) Fix urutan soal paket (tujuan asli):
--     renumber 1..N per pack + UNIQUE(pack_id, question_number).
--
-- Fresh install (schema.sql shape): Step 0-1 NO-OP (id & constraint sudah ada).
-- Local/dev yang sudah ter-apply 004 versi lama: sudah tercatat, tidak di-re-run.
-- Prod: 004 pending → menjalankan versi baru ini.
--
-- ATOMICITY: BEGIN/COMMIT eksplisit — saat manual via SQL Editor, gagal di
-- tengah = rollback penuh (tidak ada state parsial). Supabase CLI mendeteksi
-- transaction control eksplisit dan tidak membungkus ulang (no nested txn).
--
-- OPERATIONAL (prod): Step 0 (ADD COLUMN identity = table rewrite) + Step 2
-- (UPDATE semua baris) + Step 1 (drop/add PK, index rebuild) memegang lock
-- ACCESS EXCLUSIVE pada pack_questions selama 1 transaksi — untuk tabel kecil
-- (ratusan-ribuan baris) cepat, tapi jalankan di JAM SEPI karena app menulis
-- ke tabel ini saat ujian/CMS berjalan. Migration ini hanya aman dijalankan
-- sebagai role yang bypass RLS (postgres / SQL Editor) — prod mengaktifkan RLS
-- pada pack_questions tanpa policy, sehingga role non-bypass akan gagal di
-- Step 2 (UPDATE).
-- ============================================

BEGIN;

-- Step 0: pastikan kolom id ada (NO-OP di schema.sql shape).
-- GENERATED BY DEFAULT AS IDENTITY: baris existing otomatis di-backfill dengan
-- nilai sequence (1..N urutan fisik), jadi unik & langsung siap jadi PK.
ALTER TABLE public.pack_questions
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- Step 1: pastikan PK = id + UNIQUE(pack_id, question_id) ada.
-- Idempotent antar-env: pada prod PK masih komposit → diganti;
-- pada schema.sql shape PK sudah (id) → skip.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    WHERE c.conname = 'pack_questions_pkey'
      AND pg_get_constraintdef(c.oid) LIKE '%pack_id%'
  ) THEN
    ALTER TABLE public.pack_questions DROP CONSTRAINT pack_questions_pkey;
    ALTER TABLE public.pack_questions ADD PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pack_questions_pack_id_question_id_key'
  ) THEN
    ALTER TABLE public.pack_questions
      ADD CONSTRAINT pack_questions_pack_id_question_id_key
      UNIQUE (pack_id, question_id);
  END IF;
END $$;

-- Step 2: renumber seluruh paket 1..N per pack (hapus duplikat + gap data lama).
-- Urutan: question_number ASC, lalu id ASC (deterministik & stabil).
-- Idempotent: re-run pada data yang sudah 1..N menghasilkan nilai yang sama.
WITH numbered AS (
  SELECT id,
         ROW_NUMBER() OVER (
           PARTITION BY pack_id
           ORDER BY question_number ASC, id ASC
         ) AS new_num
  FROM public.pack_questions
)
UPDATE public.pack_questions pq
SET question_number = numbered.new_num
FROM numbered
WHERE pq.id = numbered.id;

-- Step 3: constraint UNIQUE(pack_id, question_number) via DO block (idempotent).
-- Postgres tidak punya ADD CONSTRAINT IF NOT EXISTS.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pack_questions_pack_id_question_number_key'
  ) THEN
    ALTER TABLE public.pack_questions
      ADD CONSTRAINT pack_questions_pack_id_question_number_key
      UNIQUE (pack_id, question_number);
  END IF;
END $$;

COMMIT;
