-- ============================================
-- 005-align-prod-schema
-- Menyamakan schema prod (dan fresh install) dengan schema.sql
-- (2026-08-12, hasil audit drift prod vs schema.sql)
-- ============================================
-- LATAR BELAKANG (audit drift 2026-08-12, dari dump schema prod):
-- Prod dibuat via SQL Editor dengan varian schema lama → beberapa drift dari
-- schema.sql. Mayoritas tidak berdampak fungsional (app memakai service_role),
-- tapi SATU drift berdampak keamanan: fresh install / local / dev TIDAK punya
-- RLS, sehingga `questions` (bank jawaban + correct_answer), `admins`
-- (password hash), dan `exam_results` bisa dibaca role anon/authenticated via
-- PostgREST (anon key publik by-design). Prod aman karena RLS aktif.
--
-- Migration ini menyamakan SEMUA drift ke bentuk schema.sql:
--   (1) RLS + deny policies            → postur keamanan prod (fresh ikut aman)
--   (2) exam_results                   → pack_id NOT NULL + FK ON DELETE CASCADE
--                                        + answers DEFAULT '{}'
--   (3) identity id                    → GENERATED BY DEFAULT
--                                        (questions, question_packs, exam_results)
--   (4) tipe kolom                     → text (+ question_type DEFAULT 'text')
--   (5) created_at default             → timezone('utc', now()) (semantik sama)
--
-- Idempotent penuh (bisa di-re-run). BEGIN/COMMIT eksplisit — saat manual via
-- SQL Editor, gagal di tengah = rollback penuh. App memakai service_role
-- (bypass RLS) → ENABLE RLS TIDAK mengubah perilaku app.
--
-- CATATAN: `pack_id SET NOT NULL` akan GAGAL (fail-fast, rollback penuh) jika
-- ada baris exam_results dengan pack_id NULL. Pre-check sebelum push:
--   SELECT count(*) FROM public.exam_results WHERE pack_id IS NULL;  -- harus 0
-- ============================================

BEGIN;

-- (1) RLS: enable di 5 tabel + deny policies di admins (idempotent)
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pack_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'admins'
                   AND policyname = 'deny_anon_admins') THEN
    CREATE POLICY deny_anon_admins ON public.admins
      TO anon USING (false) WITH CHECK (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname = 'public' AND tablename = 'admins'
                   AND policyname = 'deny_authenticated_admins') THEN
    CREATE POLICY deny_authenticated_admins ON public.admins
      TO authenticated USING (false) WITH CHECK (false);
  END IF;
END $$;

-- (2) exam_results: pack_id NOT NULL + FK ON DELETE CASCADE + answers DEFAULT
ALTER TABLE public.exam_results ALTER COLUMN pack_id SET NOT NULL;

DO $$
BEGIN
  -- hanya swap jika FK belum punya ON DELETE CASCADE (prod legacy)
  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    WHERE c.conname = 'exam_results_pack_id_fkey'
      AND pg_get_constraintdef(c.oid) NOT LIKE '%ON DELETE CASCADE%'
  ) THEN
    ALTER TABLE public.exam_results DROP CONSTRAINT exam_results_pack_id_fkey;
    ALTER TABLE public.exam_results
      ADD CONSTRAINT exam_results_pack_id_fkey
      FOREIGN KEY (pack_id) REFERENCES public.question_packs(id) ON DELETE CASCADE;
  END IF;
END $$;

ALTER TABLE public.exam_results ALTER COLUMN answers SET DEFAULT '{}'::jsonb;

-- (3) identity id → GENERATED BY DEFAULT (idempotent; ALWAYS → BY DEFAULT)
ALTER TABLE public.questions ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.question_packs ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.exam_results ALTER COLUMN id SET GENERATED BY DEFAULT;

-- (4) tipe kolom → text (varchar → text = metadata-only, tanpa rewrite)
ALTER TABLE public.questions
  ALTER COLUMN question_type TYPE text,
  ALTER COLUMN question_type SET DEFAULT 'text';
ALTER TABLE public.exam_results ALTER COLUMN participant_name TYPE text;
ALTER TABLE public.exam_results ALTER COLUMN status TYPE text;
ALTER TABLE public.question_packs ALTER COLUMN name TYPE text;

-- (5) created_at default → timezone('utc', now()) (semantik sama, eksplisit)
ALTER TABLE public.questions ALTER COLUMN created_at SET DEFAULT timezone('utc'::text, now());
ALTER TABLE public.question_packs ALTER COLUMN created_at SET DEFAULT timezone('utc'::text, now());
ALTER TABLE public.exam_results ALTER COLUMN created_at SET DEFAULT timezone('utc'::text, now());

COMMIT;
