-- ============================================================================
-- Schema Migration 000 — Initial base schema (fresh installs)
-- ============================================================================
-- WHY THIS EXISTS (2026-08-12):
-- Migrations 001-004 are RETROFITS (UPDATE/ALTER) that assume the base tables
-- already exist. `supabase db reset` rebuilds the local DB from the migrations
-- folder ONLY — the root `schema.sql` is NOT executed. So a fresh local stack
-- failed at migration-001 with:
--     ERROR: relation "questions" does not exist (SQLSTATE 42P01)
-- This migration makes fresh installs self-contained: it creates the base
-- tables exactly as root `schema.sql` does. On EXISTING installs (dev/prod)
-- every statement is a no-op (CREATE ... IF NOT EXISTS / INDEX IF NOT EXISTS),
-- so `supabase db push` is safe.
--
-- Source of truth: root `schema.sql` (keep in sync manually). Column additions
-- for later features (option_scores, subtests, ...) are owned by their own
-- migrations (002, 003) — 000 only creates the base tables + index.
-- ============================================================================
-- ATOMICITY (2026-08-12): file dibungkus BEGIN/COMMIT eksplisit — saat
-- dijalankan manual via Supabase SQL Editor (statement jalan satu-per-satu),
-- kegagalan di tengah file akan ROLLBACK penuh (tidak ada state parsial).
-- Supabase CLI mendeteksi transaction control eksplisit ini dan TIDAK
-- membungkus ulang (no nested transaction).
-- ============================================================================

BEGIN;

-- 1. Tabel Bank Soal (questions)
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,              -- Konten soal (HTML, termasuk gambar inline)
    question_type TEXT NOT NULL DEFAULT 'text', -- Tipe soal (selalu 'text' karena gambar inline di rich text editor)
    options JSONB NOT NULL,             -- {"A": "...", "B": "...", "C": "...", "D": "...", "E": "..."}
    correct_answer VARCHAR(1) NOT NULL, -- 'A', 'B', 'C', 'D', 'E'
    option_scores JSONB,                -- TKP-only: {"A":1..5,...,"E":1..5} (lihat migration-002). NULL utk TWK/TIU.
    explanation TEXT NOT NULL,          -- Pembahasan (HTML, termasuk gambar inline)
    image_url TEXT,                     -- Deprecated: gambar sekarang inline di content
    explanation_image_url TEXT,         -- Deprecated: gambar sekarang inline di explanation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Paket Soal (question_packs)
CREATE TABLE IF NOT EXISTS question_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    passing_grade INTEGER NOT NULL DEFAULT 85, -- Nilai absolut (contoh: 85 poin)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabel Relasi Paket & Soal (pack_questions)
CREATE TABLE IF NOT EXISTS pack_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
    question_number INTEGER NOT NULL,
    UNIQUE(pack_id, question_id),
    -- Race-safe (2026-08-12): satu paket TIDAK boleh punya 2 soal bernomor sama
    -- (lihat migration-004)
    UNIQUE(pack_id, question_number)
);

-- 4. Tabel Hasil Ujian (exam_results)
CREATE TABLE IF NOT EXISTS exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT REFERENCES question_packs(id) ON DELETE CASCADE NOT NULL,
    participant_name TEXT NOT NULL,
    score INTEGER NOT NULL,             -- Skor absolut (bukan persentase)
    status TEXT NOT NULL,               -- 'Lulus PG' atau 'Tidak Lulus PG'
    answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabel Admin Auth (CMS protection)
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,       -- UNIQUE untuk race-safe bootstrap
    password_hash VARCHAR(255) NOT NULL,        -- bcrypt hash (cost 10, ~60 chars)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE      -- nullable; updated on each successful login
);

-- Index untuk fast username lookup di login endpoint
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

COMMIT;
